from typing import List


def generate_answer(query: str, context_chunks: List[str]) -> str:
    """
    Placeholder LLM call.
    In a real system, integrate with an LLM endpoint (e.g., OpenAI, Azure, or a local model).
    """
    context_preview = "\n\n".join(context_chunks[:3])
    return (
        "This is a demo answer generated by a placeholder LLM.\n\n"
        f"User question:\n{query}\n\n"
        f"Top retrieved context:\n{context_preview}"
    )

